name: Publish Library Release

on:
  release:
    types: [released]


jobs:
  # Library Release Steps ##########################################################
  release-lib:
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Info
        id: info
        run: |
          echo "::set-output name=version::$(cat .lib-version)"
          echo "::set-output name=ref::${GITHUB_REF##*/}"
      - name: Decrypt secrets
        run: ./bin/decrypt-secrets
        env:
          GITHUB_SECRET_PASSPHRASE: ${{ secrets.SECRETS_TAR_PASSPHRASE }}
      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseRepository
